# Install file for brother-ql710w-cupswrapper

post_install() {
        ln -s /opt/brother/PTouch/ql710w/{inf,lpd} /usr/share/brother/PTouch/ql710w/.
        /usr/share/brother/PTouch/ql710w/cupswrapper/cupswrapperql710wpt1
        systemctl restart org.cups.cupsd.service
}

pre_remove() {
        /usr/share/brother/PTouch/ql710w/cupswrapper/cupswrapperql710wpt1 -e
}

post_remove() {
        rm /usr/share/brother/PTouch/ql710w/{inf,lpd}
        systemctl restart org.cups.cupsd
}
